import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="max-w-xl mx-auto px-4 py-8 space-y-4 text-sm leading-relaxed">
      
      {/* Back to home */}
      <Link
        href="/"
        className="text-xs text-muted-foreground hover:text-foreground"
      >
        ← Back to home
      </Link>
      
      <h1 className="text-xl font-semibold">Terms of Use</h1>

      <p>
        This app was created by <strong>Evans Munsha</strong> to solve a very
        personal, everyday problem.
      </p>

      <p>
        The goal of this app was never to compete with existing tools, but to
        build something that:
      </p>

      <ul className="list-disc pl-5 space-y-1">
        <li>Solves one clear problem well</li>
        <li>Matches the real workflow of field ministry</li>
        <li>Stays simple, distraction-free, and respectful</li>
      </ul>

      <p>
        After proving useful personally, it was shared publicly so others with
        the same need could benefit from it freely.
      </p>

      <p>
        While regularly engaging in field ministry, time was recorded manually
        in a small notebook. Although simple, this approach made time
        calculations difficult, especially when adding up multiple start and
        end times across many days.
      </p>

      <p className="italic text-muted-foreground">
        09:30 – 15:30 · 07:30 – 15:30 · 09:20 – 15:30 · 08:30 – 19:40
      </p>

      <p>
        At the end of each month, calculating total hours and tracking Bible
        studies became time-consuming and error-prone.
      </p>

      <p className="font-medium">This app exists to remove that friction.</p>

      <ul className="list-disc pl-5 space-y-1">
        <li>Automatically calculates hours</li>
        <li>Organizes daily entries</li>
        <li>Summarizes monthly activity</li>
        <li>Keeps records simple and clear</li>
      </ul>

      <h2 className="text-base font-medium pt-4">Use of the app</h2>
      <p>
        This app is provided free of charge and is intended for personal,
        voluntary use. There are no guarantees of availability, accuracy, or
        long-term support.
      </p>

      <p>
        You are responsible for the data you enter and how you use the reports
        generated by the app.
      </p>

      <h2 className="text-base font-medium pt-4">Good faith</h2>
      <p>
        This project is shared in good faith, with no intent to cause harm,
        collect unnecessary data, or impose obligations on users.
      </p>

      <p className="text-base text-muted-foreground pt-6 text-center">
        By using this app, you agree to these simple terms.
      </p>
    </div>
  )
}
